#!/bin/bash


if [ $1 = 'd' -o $1 = 'D' ]; then
	echo 'delete files'
	find /home/tjahn/Git2/User/kyulhee/DNN/Tensor/BDLAB_ML_Library -maxdepth 1 -name "*.csv" -delete
	find /home/tjahn/Git2/User/kyulhee/DNN/Tensor/models -maxdepth 1 -name "model*" -delete
	find /home/tjahn/Git2/User/kyulhee/DNN/Tensor/result -maxdepth 1 -name "*.csv" -delete

elif [ $1 = 's' -o $1 = 'S' ]; then
	echo 'save files. pathway: '
	if [ -n $2 ]; then
		echo $2
		mkdir -v '/home/tjahn/Git2/User/kyulhee/DNN/Tensor/result/'$2 
		mkdir -v '/home/tjahn/Git2/User/kyulhee/DNN/Tensor/models/'$2
		find /home/tjahn/Git2/User/kyulhee/DNN/Tensor/BDLAB_ML_Library -maxdepth 1 -name "*.csv" -exec mv {} /home/tjahn/Git2/User/kyulhee/DNN/Tensor/models/$2 \;
		find /home/tjahn/Git2/User/kyulhee/DNN/Tensor/models -maxdepth 1 -name "model*" -exec mv {} /home/tjahn/Git2/User/kyulhee/DNN/Tensor/models/$2 \;
		find /home/tjahn/Git2/User/kyulhee/DNN/Tensor/result -maxdepth 1 -name "*.csv" -exec mv {} /home/tjahn/Git2/User/kyulhee/DNN/Tensor/result/$2 \;
		echo '/home/tjahn/Git2/User/kyulhee/DNN/Tensor/result/'$2
	else
		echo "pathway가 잘못됐습니다. 다시 입력해주세요."
	fi
else
	echo "옵션이 잘못됐습니다. d/D: delete result & model, s '/pathway/directory': save result & model to pathway"
fi
#ls /home/tjahn/Git2/User/kyulhee/DNN/Tensor/BDLAB_ML_Library | grep result | xargs rm
#ls /home/tjahn/Git2/User/kyulhee/DNN/Tensor/models | grep model | xargs rm
#ls /home/tjahn/Git2/User/kyulhee/DNN/Tensor/result | grep result | xargs rm
